# .github/workflows/cron.yml
name: Trigger Website Cache Invalidation once per night
on:
    schedule:
        - cron: "0 5 * * *" # every night at 5 AM
jobs:
    ping-vercel:
        runs-on: ubuntu-latest
        steps:
            - name: Curl scheduled endpoint
              run: curl https://syntax-error.se/api/revalidate/
